#
# Circle CI 2.0 Docs
# 
# For info, see: https://circleci.com/docs/2.0/
#

version: 2
jobs:
  build:
    docker:
      - image: newtonsystems/tools-docker-grpc-tools:0.2.0
    environment:
      TEST_REPORTS: /tmp/test-reports
      COVERALLS_REPO_TOKEN: ien2C1f5InnEFCI33oPei3wsn71TFvVZQ
    working_directory: ~/libutils
    steps:
      - checkout

      - run:
          name: Clone dev-utils repo (Development utility scripts/tools)
          command: |
            cd ~/
            git clone -b $CIRCLE_BRANCH https://github.com/newtonsystems/dev-utils.git

      - run:
          name: Clone devops repo (Update the submodule to the latest change)
          command: |
            cd ~/
            git clone -b $CIRCLE_BRANCH https://github.com/newtonsystems/devops.git
            cd devops
            git submodule sync
            git submodule update --init
            git submodule foreach git pull origin $CIRCLE_BRANCH

      # Install Python py.test tools. (TODO: Skip download if already in cache.)
      - run:
          name: Install python requirements & pytest tools
          command: |
            pip install grpcio grpcio-tools
            pip install -r requirements.txt
            pip install -e .
            pip install pytest
            pip install pytest-cov
            pip install python-coveralls

      - run:
          name: Run py.test & coverage report against libutils package
          command: |
            py.test --cov --cov-report html:${TEST_REPORTS} --junitxml=${TEST_REPORTS}/pytest/junit.xml tests/

      - deploy:
          name: Upload coverage results to coveralls
          command: |
            coveralls

      - deploy:
          name: Make and deploy sphinx documentation
          command: |
              # NOTE: At the moment even no changes are packaged up into
              #       a new python devpi package
              make html
              ~/dev-utils/bin/deploy_sphinx_docs.sh libutils docs/build/html/

      - deploy:
          name: Deploy python package to devpi 
          command: |
              # NOTE: At the moment even no changes are packaged up into
              #       a new python devpi package
              ~/devops/scripts/circle-upload-devpi.sh

      # Upload test results
      - store_test_results:
          path: /tmp/test-reports

