#
# Circle CI 2.0 Docs
# 
# For info, see: https://circleci.com/docs/2.0/
#

version: 2
jobs:
  build:
    docker:
      - image: newtonsystems/tools-docker-grpc-tools:0.2.0
    working_directory: ~/libutils
    steps:
      - checkout

      - run:
          name: Clone devops repo (Update the submodule to the latest change)
          command: |
            git clone -b $CIRCLE_BRANCH https://github.com/newtonsystems/devops.git
            cd devops
            git submodule sync
            git submodule update --init
            git submodule foreach git pull origin $CIRCLE_BRANCH

      # Install Python py.test tools. (TODO: Skip download if already in cache.)
      - run:
          name: Install python requirements & pytest tools
          command: |
            pip install grpcio grpcio-tools
            pip install -r requirements.txt
            pip install -e .
            pip install pytest
            pip install pytest-cov

      - run:
          name: Run py.test & coverage report against libutils package
          command: |
            mkdir -p $CIRCLE_TEST_REPORTS/pytest
            py.test --cov --cov-report html:$CIRCLE_TEST_REPORTS --junitxml=$CIRCLE_TEST_REPORTS/pytest/junit.xml tests/

      - deploy:
          name: Deploy python package to devpi 
          command: |
              # NOTE: At the moment even no changes are packaged up into
              #       a new python devpi package
              cd python
              ../devops/scripts/circle-upload-devpi.sh

